### ISSUE TITLE
Can't create base directory

### ISSUE THREAD

**Issue by amit2014** [sazncode/BingRewards#24]
[8788:14004:0914/073649.932:ERROR:util.cc(129)] Can't create base directory: C:\Program Files\Google\GoogleUpdater
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="daily-sets"]/mee-card-group[1]/div/mee-card[1]/div/card-content/mee-rewards-daily-set-item-content/div/a/mee-rewards-points/div/div/span[1]"}
  (Session info: chrome=105.0.5195.127)
Stacktrace:
Backtrace:
        Ordinal0 [0x0090DF13+2219795]
        Ordinal0 [0x008A2841+1779777]
        Ordinal0 [0x007B423D+803389]
        Ordinal0 [0x007E3025+995365]
        Ordinal0 [0x007E31EB+995819]
        Ordinal0 [0x00810F52+1183570]
        Ordinal0 [0x007FE844+1108036]
        Ordinal0 [0x0080F192+1175954]
        Ordinal0 [0x007FE616+1107478]
        Ordinal0 [0x007D7F89+950153]
        Ordinal0 [0x007D8F56+954198]
        GetHandleVerifier [0x00C02CB2+3040210]
        GetHandleVerifier [0x00BF2BB4+2974420]
        GetHandleVerifier [0x009A6A0A+565546]
        GetHandleVerifier [0x009A5680+560544]
        Ordinal0 [0x008A9A5C+1808988]
        Ordinal0 [0x008AE3A8+1827752]
        Ordinal0 [0x008AE495+1827989]
        Ordinal0 [0x008B80A4+1867940]
        BaseThreadInitThunk [0x76B2FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77527B5E+286]
        RtlGetAppContainerNamedObjectPath [0x77527B2E+238]

Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="daily-sets"]/mee-card-group[1]/div/mee-card[3]/div/card-content/mee-rewards-daily-set-item-content/div/a/mee-rewards-points/div/div/span[1]"}
  (Session info: chrome=105.0.5195.127)
Stacktrace:
Backtrace:
        Ordinal0 [0x0090DF13+2219795]
        Ordinal0 [0x008A2841+1779777]
        Ordinal0 [0x007B423D+803389]
        Ordinal0 [0x007E3025+995365]
        Ordinal0 [0x007E31EB+995819]
        Ordinal0 [0x00810F52+1183570]
        Ordinal0 [0x007FE844+1108036]
        Ordinal0 [0x0080F192+1175954]
        Ordinal0 [0x007FE616+1107478]
        Ordinal0 [0x007D7F89+950153]
        Ordinal0 [0x007D8F56+954198]
        GetHandleVerifier [0x00C02CB2+3040210]
        GetHandleVerifier [0x00BF2BB4+2974420]
        GetHandleVerifier [0x009A6A0A+565546]
        GetHandleVerifier [0x009A5680+560544]
        Ordinal0 [0x008A9A5C+1808988]
        Ordinal0 [0x008AE3A8+1827752]
        Ordinal0 [0x008AE495+1827989]
        Ordinal0 [0x008B80A4+1867940]
        BaseThreadInitThunk [0x76B2FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77527B5E+286]
        RtlGetAppContainerNamedObjectPath [0x77527B2E+238]

**Comment by sazncode** [comment]
Hello there,

I haven't been able to replicate this error, however upon investigating others with similar errors have been able to fix this error by manually creating creating the directory:

C:\Program Files\Google\GoogleUpdater
![image](https://user-images.githubusercontent.com/80719066/190247924-6ebc866a-8418-47a3-a743-8da1bc45773c.png)

Please check to ensure you have GoogleUpdater folder on your computer at C:\Program Files\Google
