### ISSUE TITLE
Architecture Error running on Raspberry Pi 4

### ISSUE THREAD

**Issue by hexiro** [sazncode/BingRewards#25]
Error:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error
```
Command:
```
docker run -it --env-file ./BingRewards.env --restart unless-stopped --name bing-rewards nelsondane/bing-rewards:latest
```

**Comment by NelsonDane** [comment]
Hello, thanks for your interest in the bot! Unfortunately Raspberry Pi's don't support Google Chrome, which is what the bot uses at the moment. Perhaps in the future we'll add some variations for other architectures

**Comment by hexiro** [comment]
> Hello, thanks for your interest in the bot! Unfortunately Raspberry Pi's don't support Google Chrome, which is what the bot uses at the moment. Perhaps in the future we'll add some variations for other architectures

Ah I see. I've had issues in the past with Google Chrome on Raspberry Pis. Is there a reason this couldn't run on Chromium though? From my experience, the only time I needed Google Chrome over Chromium was for the mp4 codecs which Chromium doesn't have. If the bot doesn't rely on that I'd like to give Chromium a swing!

**Comment by NelsonDane** [comment]
> > Hello, thanks for your interest in the bot! Unfortunately Raspberry Pi's don't support Google Chrome, which is what the bot uses at the moment. Perhaps in the future we'll add some variations for other architectures
> 
> Ah I see. I've had issues in the past with Google Chrome on Raspberry Pis. Is there a reason this couldn't run on Chromium though? From my experience, the only time I needed Google Chrome over Chromium was for the mp4 codecs which Chromium doesn't have. If the bot doesn't rely on that I'd like to give Chromium a swing!

You're right that the bot doesn't require Google Chrome over Chromium, so I've pushed an update to `nelsondane/bing-rewards:beta` that (hopefully) uses Chromium if the architecture `arm64` is detected. I don't have a device to test it with currently, but if you could give it a try that would be much appreciated!

**Comment by hexiro** [comment]
> > > Hello, thanks for your interest in the bot! Unfortunately Raspberry Pi's don't support Google Chrome, which is what the bot uses at the moment. Perhaps in the future we'll add some variations for other architectures
> 
> > 
> 
> > Ah I see. I've had issues in the past with Google Chrome on Raspberry Pis. Is there a reason this couldn't run on Chromium though? From my experience, the only time I needed Google Chrome over Chromium was for the mp4 codecs which Chromium doesn't have. If the bot doesn't rely on that I'd like to give Chromium a swing!
> 
> 
> 
> You're right that the bot doesn't require Google Chrome over Chromium, so I've pushed an update to `nelsondane/bing-rewards:beta` that (hopefully) uses Chromium if the architecture `arm64` is detected. I don't have a device to test it with currently, but if you could give it a try that would be much appreciated!

Cool, Thanks! I'll try it and get back to you

**Comment by hexiro** [comment]
> > > Hello, thanks for your interest in the bot! Unfortunately Raspberry Pi's don't support Google Chrome, which is what the bot uses at the moment. Perhaps in the future we'll add some variations for other architectures
> > 
> > 
> > Ah I see. I've had issues in the past with Google Chrome on Raspberry Pis. Is there a reason this couldn't run on Chromium though? From my experience, the only time I needed Google Chrome over Chromium was for the mp4 codecs which Chromium doesn't have. If the bot doesn't rely on that I'd like to give Chromium a swing!
> 
> You're right that the bot doesn't require Google Chrome over Chromium, so I've pushed an update to `nelsondane/bing-rewards:beta` that (hopefully) uses Chromium if the architecture `arm64` is detected. I don't have a device to test it with currently, but if you could give it a try that would be much appreciated!

I see that you just pushed to DockerHub which initially got it up and running. Still, it looks like after it downloads chromedriver it crashes because chromedriver is the wrong architecture?
```
rm: cannot remove '/tmp/.X99-lock': No such file or directory
Starting X virtual framebuffer (Xvfb) in background...
Starting Bing Rewards Bot...
Current IPv4 Address: [Redacted]
Unable to get IPv6 address


Starting Bing Rewards Automation:       2022-10-16 14:25:00.488836-04:00

[WDM] - Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 6.35M/6.35M [00:00<00:00, 14.1MB/s]
```
```py
Traceback (most recent call last):
  File "/app/main.py", line 635, in getDriver
    driver = webdriver.Chrome(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/common/service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/root/.wdm/drivers/chromedriver/linux64/106.0.5249/chromedriver'
```

**Comment by daVinci13** [comment]
Similar thing...
```
Starting Bing Rewards Automation:       2022-10-16 21:28:02.279277+02:00

Traceback (most recent call last):
  File "/app/main.py", line 638, in getDriver
    driver = webdriver.Chrome(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/common/service.py", line 110, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/106.0.5249/chromedriver unexpectedly exited. Status code was: 255
```

**Comment by sazncode** [comment]
Hello there!

We've just added support for Edge and Firefox. Please try running the bot with HANDLE_DRIVER set as True and BROWSER set to edge or firefox.

**Comment by hexiro** [comment]
> Unfortunately, we are unable to confidently implement a solution for this issue as the none of the active collaborators of this repository possess or have access to a Raspberry Pi to test with. Should that change sometime into the future, we will consider adding that support.

I understand. I'll do a little digging and let you know if I find anything :)

**Comment by daVinci13** [comment]
@Prem-ium I have ARM device, could test the images if you want!?

**Comment by hejun041** [comment]
`  File "main.py", line 339, in get_driver
    driver = webdriver.Firefox(
  File "/root/br/BingRewards/venv/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 68, in __init__
    super().__init__(command_executor=executor, options=self.options)
  File "/root/br/BingRewards/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/root/br/BingRewards/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/root/br/BingRewards/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/root/br/BingRewards/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line
`
